services:
  umami:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_URL_UMAMI_3000
      - 'DATABASE_URL=$UMAMI_DATABASE_URL'
      - DATABASE_TYPE=postgres
      - APP_SECRET=$SERVICE_PASSWORD_64_UMAMI
